# Generated by Django 5.1.1 on 2024-09-26 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Member",
        ),
    ]
