# Generated by Django 5.1.1 on 2024-09-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_remove_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default="default_password", max_length=128),
        ),
    ]
