# Generated by Django 5.1.1 on 2024-09-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_remove_member_password_alter_member_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="unit",
            field=models.CharField(max_length=50),
        ),
    ]
