# Generated by Django 5.1.1 on 2024-09-23 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_alter_user_password"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="firstname",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="lastname",
            new_name="last_name",
        ),
    ]
